package com.multind.bitpongo.notification;

public enum NotificationEventType {
    SCHEDULER_FATAL,
    ORDER_MANUAL_REVIEW,
    TRADE_FAILED,
    MARKET_OUTAGE,
    PLAN_EXECUTION_SKIPPED,
    PLAN_EXECUTION_DELAYED,
    TRADE_SUCCEEDED,
    ASSET_SNAPSHOT_FAILED,
    SYSTEM_RECOVERED,
    SERVICE_STARTED,
    BARK_TEST
}
